#!/bin/sh

export PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH"
# make -j3 RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0 TESTS=0 LINTJSON=0 ASTYLE=0
# make -j3 RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0 TESTS=0 LINTJSON=0 ASTYLE=0 LTO=1

# make -j3 RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0 TESTS=0 LINTJSON=0 ASTYLE=0 LTO=1 CLANG=1
make -j3 RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0 TESTS=0 LINTJSON=0 ASTYLE=0 LTO=0 CLANG=1 CCACHE=1
